% File:             vdriadDrawFiguresMain.m
% Author:           Jorge Augusto Martinez-Ortiz
% Date Created:     02.06.2023

function vdriadDrawFiguresMain(app)
%vdriadDrawFiguresMain Draws the figures displayed in the main function
%   Detailed explanation goes here

    % UPDATE 'PARTICLE TRAJECTORIES' TABLE
    N = 1:app.NUM_PARTICLES;
    app.UITable.Data = table(N',...
                             app.dust.host.x,...
                             app.dust.host.y,...
                             app.dust.host.z,...
                             app.dust.host.vx,...
                             app.dust.host.vy,...
                             app.dust.host.vz,...
                             app.dust.host.ax,...
                             app.dust.host.ay,...
                             app.dust.host.az);
end