function vdriadCalculatePositions(Dust,Parameters,kernel,totalTime)
%CalculatePositions Launches CUDA kernel that will update the positions of the particles
%   kernel:         CUDA kernel stored in matlab as a function handle
    [...
    Dust.Position.Device.x,Dust.Position.Device.y,Dust.Position.Device.z,...
    Dust.Velocity.Device.x,Dust.Velocity.Device.y,Dust.Velocity.Device.z,...
    Dust.Acceleration.Device.x,Dust.Acceleration.Device.y,Dust.Acceleration.Device.z,...
    ] = feval(...
        kernel,...
        Dust.Position.Device.x,Dust.Position.Device.y,Dust.Position.Device.z,...
        Dust.Velocity.Device.x,Dust.Velocity.Device.y,Dust.Velocity.Device.z,...
        Dust.Acceleration.Device.x,Dust.Acceleration.Device.y,Dust.Acceleration.Device.z,...
        Parameters.TIME_STEP,...
        totalTime,...
        Parameters.NUM_PARTICLES);
end
