% update variable names so that it matches syntax of calculateForces
function vdriadCalculatePositions(Dust,Parameters,kernel,totalTime)
%UNTITLED6 Summary of this function goes here
%   Detailed explanation goes here
    [Dust.Position.Device.x,Dust.Position.Device.y,Dust.Position.Device.z,...
     Dust.Velocity.Device.x,Dust.Velocity.Device.y,Dust.Velocity.Device.z,...
     Dust.Acceleration.Device.x,Dust.Acceleration.Device.y,Dust.Acceleration.Device.z,...
     ] = feval(kernel, ...
        Dust.Position.Device.x,Dust.Position.Device.y,Dust.Position.Device.z,...
        Dust.Velocity.Device.x,Dust.Velocity.Device.y,Dust.Velocity.Device.z,...
        Dust.Acceleration.Device.x,Dust.Acceleration.Device.y,Dust.Acceleration.Device.z,...
        Parameters.TIME_STEP,...
        totalTime,...
        Parameters.NUM_PARTICLES);
end
