% update variable names so that it matches syntax of calculateForces
function dust = vdriadCalculatePositions(dust,params,kernel,totalTime);
%UNTITLED6 Summary of this function goes here
%   Detailed explanation goes here
    [Dust.Position.Device.x,Dust.Position.Device.z,Dust.Position.Device.z,...
     Dust.Velocity.Device.x,Dust.Velocity.Device.z,Dust.Velocity.Device.z,...
     Dust.Acceleration.Device.x,Dust.Acceleration.Device.y,Dust.Acceleration.Device.z,...
     Dust.Radius.Device,...
     Dust.Mass.Device,...
     Dust.Charge.Device,...
     Dust.WakeCharge.Device,...
     Dust.WakeLength.Device,...
     Dust.WakeNNZ.Device,...
     Dust.WakeNNR.Device,...
     Dust.WakeNNId.Device] = feval(kernel, ...
                        Dust.Position.Device.x,Dust.Position.Device.z,Dust.Position.Device.z,...
                        Dust.Velocity.Device.x,Dust.Velocity.Device.z,Dust.Velocity.Device.z,...
                        Dust.Acceleration.Device.x,Dust.Acceleration.Device.y,Dust.Acceleration.Device.z,...
                        Dust.Radius.Device,...
                        Dust.Mass.Device,...
                        Dust.Charge.Device,...
                        Dust.WakeCharge.Device,...
                        Dust.WakeLength.Device,...
                        Dust.WakeNNZ.Device,...
                        Dust.WakeNNR.Device,...
                        Dust.WakeNNId.Device,...
                        Parameters.DUST_CHARGE_DENSITY_MEAN,... 
                        Parameters.ELECTRON_CHARGE,...
                        Parameters.CUTOFF_MULTIPLIER,...
                        Parameters.WAKE_CHARGE_RATIO,...
                        Parameters.WAKE_LENGTH,...
                        Parameters.ION_DEBYE,...
                        Parameters.ELECTRON_DEBYE,...
                        Parameters.TIME_STEP,...
                        totalTime,...
                        Parameters.NUM_PARTICLES);
end
