function vdriadCalculateForces(Dust,Parameters,kernel)
%CalculateForces Function to Calculate the forces of the interacting dust
%particles and ion wakes.
    % Time to seed the random number generator
    seed = convertTo(datetime('now'),'posixtime');

    % CALCULATE THE FORCES
    [Dust.Position.Device.x,Dust.Position.Device.y,Dust.Position.Device.z,...
     Dust.Velocity.Device.x,Dust.Velocity.Device.y,Dust.Velocity.Device.z,...
     Dust.Acceleration.Device.x,Dust.Acceleration.Device.y,Dust.Acceleration.Device.z,...
     Dust.Radius.Device,...
     Dust.Mass.Device,...
     Dust.Charge.Device,...
     Dust.WakeCharge.Device,...
     Dust.WakeLength.Device,...
     Dust.WakeNNZ.Device,...
     Dust.WakeNNR.Device,...
     Dust.WakeNNId.Device] = feval(kernel,...
                             Dust.Position.Device.x,Dust.Position.Device.y,Dust.Position.Device.z,...
                             Dust.Velocity.Device.x,Dust.Velocity.Device.y,Dust.Velocity.Device.z,...
                             Dust.Acceleration.Device.x,Dust.Acceleration.Device.y,Dust.Acceleration.Device.z,...
                             Dust.Radius.Device,...
                             Dust.Mass.Device,...
                             Dust.Charge.Device,...
                             Dust.WakeCharge.Device,...
                             Dust.WakeLength.Device,...
                             Dust.WakeNNZ.Device,...
                             Dust.WakeNNR.Device,...
                             Dust.WakeNNId.Device,...
                             Parameters.DUST_RADIUS_MEAN,...
                             Parameters.COULOMB,...
                             Parameters.ION_DEBYE,...
                             Parameters.ELECTRON_DEBYE,...
                             Parameters.CUTOFF_M,...
                             Parameters.RADIAL_CONFINEMENT_COEFF,...
                             Parameters.CELL_RADIUS,...
                             Parameters.E_FIELD_COEFF,...
                             Parameters.CELL_HEIGHT,...
                             Parameters.SHEATH_HEIGHT,...
                             Parameters.WAKE_CHARGE_RATIO,...
                             Parameters.GRAVITY,...
                             Parameters.GAS_TEMPERATURE,...
                             Parameters.GAS_PRESSURE,...
                             Parameters.TIME_STEP,...
                             seed,...
                             Parameters.NUM_PARTICLES);
end